CREATE TABLE IF NOT EXISTS clients (
  id int AUTO_INCREMENT PRIMARY KEY,
  firstName nvarchar(255) NOT NULL,
  lastName nvarchar(255) NOT NULL,
  birthday date,
  gender varchar(64),  /*Gender constraint at front end */
  dateOfIntake DATE NOT NULL,
  phone VARCHAR(15),
  smsConsent BOOLEAN,
  homeStreet VARCHAR(255),
  homeCity VARCHAR(255),
  homeState VARCHAR(2),
  homeZip VARCHAR(10),
  email VARCHAR(255),
  civilStatus ENUM('single', 'married', 'commonLawMarriage', 'divorced', 'widowed'),
  countryOfOrigin VARCHAR(2),
  dateOfUSArrival DATE,
  primaryLanguage VARCHAR(64),
  currentlyEmployed BOOLEAN,
  employmentSector VARCHAR(255),
  annualIncome INT,
  householdSize INT,
  isStudent BOOLEAN,
  eligibleToVote BOOLEAN,
  clientSource VARCHAR(64),
  couldVolunteer BOOLEAN,

  dateAdded DATETIME DEFAULT CURRENT_TIMESTAMP,
  dateModified DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  addedBy int NOT NULL /*Self Reference to User ID*/,
  modifiedBy int NOT NULL /*Self Reference to User ID*/,
  FOREIGN KEY (addedBy) REFERENCES users(id),
  FOREIGN KEY (modifiedBy) REFERENCES users(id)
);