/* Replace with your SQL commands */
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS contacts;
DROP TABLE IF EXISTS demographics;
DROP TABLE IF EXISTS programs;
DROP TABLE IF EXISTS services;
DROP TABLE IF EXISTS intakeData;
DROP TABLE IF EXISTS clinets;
DROP TABLE IF EXISTS intakeServices;
DROP TABLE IF EXISTS users;
SET FOREIGN_KEY_CHECKS=1;