ALTER TABLE clientFiles
ADD COLUMN clientId INT NOT NULL,
ADD CONSTRAINT fk_file_client_id FOREIGN KEY (clientId) REFERENCES clients(id),
MODIFY s3Key VARCHAR(256) NOT NULL,
MODIFY fileSize INT NOT NULL,
MODIFY fileExtension VARCHAR(32) NOT NULL,
MODIFY isDeleted BOOLEAN DEFAULT false NOT NULL,
MODIFY dateAdded DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
;