name: Build and deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - name: echo actor
        run: |
          echo "Full name"
          echo $GITHUB_REPOSITORY
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.14.1
      - run: pnpm install
      - run: pnpm run typescript
      - run: pnpm run check-format
      - run: pnpm run lint
      - run: pnpm run build
      - run: find static -type f ! -path static/manifest.json -exec gzip -9 {} \; -exec mv {}.gz {} \;
      - run: ls -al
      - name: "Upload frontend artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: static-assets
          path: static
  deploy-frontend:
    if: github.ref == 'refs/heads/master' && $GITHUB_REPOSITORY == 'JustUtahCoders/comunidades-unidas-internal'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: static-assets
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: comunidades-unidas-frontend-assets
          source_dir: static
  deploy-server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && $GITHUB_REPOSITORY == 'JustUtahCoders/comunidades-unidas-internal'
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: "deploy comunidades-unidas-prod-2"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
