name: Build and deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: pnpm/action-setup@v2
        with:
          version: 8.2.0
          dest: ~/.pnpm-store
      - run: pnpm install
      - run: pnpm run typescript
      - run: pnpm run check-format
      - run: pnpm run lint
      - run: PUBLIC_PATH=https://comunidades-unidas-frontend-assets.s3.amazonaws.com/ pnpm run build
      - run: find static -type f ! -path static/manifest.json -exec gzip -9 {} \; -exec mv {}.gz {} \;
      - run: find static
      - name: "Upload frontend artifacts"
        uses: actions/upload-artifact@v2
        with:
          name: static-assets
          path: static
  deploy-frontend:
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'JustUtahCoders'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: static-assets
      - uses: joeldenning/upload-s3-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: comunidades-unidas-frontend-assets
          source_dir: .
          destination_dir: .
  deploy-server:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'JustUtahCoders'
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: static-assets
          path: static
      - run: rm docker-compose.yml
      - run: find .
      - uses: joeldenning/actions-aws-eb@master
        with:
          command: "deploy dockerized"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
