name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build
        uses: tomchv/wait-my-workflow@v1.1.0
        id: wait-build
        with:
          token: ${{ secrets.WAIT_TOKEN }}
          checkName: build
      - name: Build failed
        if: steps.wait-build.outputs.conclusion == 'failure'
        run: echo "Build failed" && false
      - name: No build found
        if: steps.wait-build.outputs.conclusion == 'does not exist'
        run: echo "Build doesn't exist" && false
      - name: Build timeout
        if: steps.wait-build.outputs.conclusion == 'does not exist'
        run: echo "Build timed out" && false
      - uses: actions/download-artifact@v2
        with:
          name: static-assets
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: comunidades-unidas-frontend-assets
          source_dir: static

  deploy-server:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build
        uses: tomchv/wait-my-workflow@v1.1.0
        id: wait-build
        with:
          token: ${{ secrets.WAIT_TOKEN }}
          checkName: build
      - name: Build failed
        if: steps.wait-build.outputs.conclusion == 'failure'
        run: echo "Build failed" && false
      - name: No build found
        if: steps.wait-build.outputs.conclusion == 'does not exist'
        run: echo "Build doesn't exist" && false
      - name: Build timeout
        if: steps.wait-build.outputs.conclusion == 'does not exist'
        run: echo "Build timed out" && false
      - uses: actions/checkout@v2
      - uses: hmanzur/actions-aws-eb@v1.0.0
        with:
          command: "deploy comunidades-unidas-prod-2"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
